version: '3'

services:
  backend-django:
    build: ./backend_books_review
    container_name: backend-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_books_review:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
