# Generated by Django 5.1.2 on 2024-11-09 13:11

import books.utilities
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Такая книга уже есть в архиве.'}, help_text='Название книги', max_length=200, unique=True, verbose_name='Название')),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='Без описания.', help_text='Описание книги', null=True, verbose_name='Описание')),
                ('release_date', models.DateField(blank=True, help_text='Дата издания', null=True, verbose_name='Издана')),
                ('cover_img', models.ImageField(blank=True, upload_to=books.utilities.get_timestamp_path, verbose_name='Обложка')),
                ('publicated', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Проверено модератором?')),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
