# Generated by Django 5.1.2 on 2024-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Неизвестен', max_length=200, verbose_name='Автор книги'),
        ),
    ]
