# Generated by Django 5.1.2 on 2024-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Оценка книги от 0 до 5', max_length=5, null=True, verbose_name='Оценка'),
        ),
    ]
